// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_turn_clocks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSessionTurnClock = `-- name: AdvanceSessionTurnClock :one
WITH previous AS (
    SELECT last_response_ended_at, last_served_model
    FROM router.session_turn_clocks
    WHERE installation_id = $1::uuid
      AND session_key = $2::bytea
),
advanced AS (
    INSERT INTO router.session_turn_clocks (
        installation_id,
        session_key,
        last_response_ended_at,
        last_served_model
    ) VALUES (
        $1::uuid,
        $2::bytea,
        $3::timestamptz,
        $4::varchar
    )
    ON CONFLICT (installation_id, session_key) DO UPDATE
    SET last_response_ended_at = EXCLUDED.last_response_ended_at,
        last_served_model = EXCLUDED.last_served_model,
        updated_at = now()
    WHERE router.session_turn_clocks.last_response_ended_at < EXCLUDED.last_response_ended_at
)
SELECT
    previous.last_response_ended_at AS previous_response_ended_at,
    previous.last_served_model AS previous_served_model
FROM (SELECT 1) AS anchor
LEFT JOIN previous ON true
`

type AdvanceSessionTurnClockParams struct {
	InstallationID  uuid.UUID
	SessionKey      []byte
	ResponseEndedAt pgtype.Timestamptz
	ServedModel     string
}

type AdvanceSessionTurnClockRow struct {
	PreviousResponseEndedAt pgtype.Timestamptz
	PreviousServedModel     *string
}

// Records that a session's main thread finished a response and returns the
// finish recorded before it, so the caller can time the next typed prompt.
// Racing completions keep the latest finish. Every CTE reads the same
// snapshot, so previous sees the row before advanced rewrites it; the anchor
// row turns a session's first advance into a NULL result instead of no rows.
//
//	WITH previous AS (
//	    SELECT last_response_ended_at, last_served_model
//	    FROM router.session_turn_clocks
//	    WHERE installation_id = $1::uuid
//	      AND session_key = $2::bytea
//	),
//	advanced AS (
//	    INSERT INTO router.session_turn_clocks (
//	        installation_id,
//	        session_key,
//	        last_response_ended_at,
//	        last_served_model
//	    ) VALUES (
//	        $1::uuid,
//	        $2::bytea,
//	        $3::timestamptz,
//	        $4::varchar
//	    )
//	    ON CONFLICT (installation_id, session_key) DO UPDATE
//	    SET last_response_ended_at = EXCLUDED.last_response_ended_at,
//	        last_served_model = EXCLUDED.last_served_model,
//	        updated_at = now()
//	    WHERE router.session_turn_clocks.last_response_ended_at < EXCLUDED.last_response_ended_at
//	)
//	SELECT
//	    previous.last_response_ended_at AS previous_response_ended_at,
//	    previous.last_served_model AS previous_served_model
//	FROM (SELECT 1) AS anchor
//	LEFT JOIN previous ON true
func (q *Queries) AdvanceSessionTurnClock(ctx context.Context, arg AdvanceSessionTurnClockParams) (AdvanceSessionTurnClockRow, error) {
	row := q.db.QueryRow(ctx, advanceSessionTurnClock,
		arg.InstallationID,
		arg.SessionKey,
		arg.ResponseEndedAt,
		arg.ServedModel,
	)
	var i AdvanceSessionTurnClockRow
	err := row.Scan(&i.PreviousResponseEndedAt, &i.PreviousServedModel)
	return i, err
}

const sweepStaleSessionTurnClocks = `-- name: SweepStaleSessionTurnClocks :exec
DELETE FROM router.session_turn_clocks
WHERE updated_at < now() - interval '7 days'
`

// Deletes clocks for sessions idle more than seven days. A prompt after that
// long starts a new sitting rather than answering the previous response.
//
//	DELETE FROM router.session_turn_clocks
//	WHERE updated_at < now() - interval '7 days'
func (q *Queries) SweepStaleSessionTurnClocks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, sweepStaleSessionTurnClocks)
	return err
}
